version: '3'

services:
  db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: spring_crud_users_test

  testenv:
    build: .
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/spring_crud_users_test?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=password
    depends_on:
      - db
    links:
      - db
