export const BASE_URL = '/cars'

export const GET_ALL_LOCS_PENDING = 'GET_ALL_LOCS_PENDING'
//
export const GET_ALL_LOCS_SUCCESS = 'GET_ALL_LOCS_SUCCESS'
export const GET_ALL_LOCS_FAILED = 'GET_ALL_LOCS_FAILED'
export const GET_ONE_LOC_PENDING = 'GET_ONE_LOC_PENDING'
export const GET_ONE_LOC_SUCCESS = 'GET_ONE_LOC_SUCCESS'
export const GET_ONE_LOC_FAILED = 'GET_ONE_LOC_FAILED'

export const DELETE_ONE_LOC_SUCCESS = 'DELETE_ONE_LOC_SUCCESS'
export const DELETE_ONE_LOC_FAILED = 'DELETE_ONE_LOC_FAILED'
export const DELETE_ONE_LOC_PENDING = 'DELETE_ONE_LOC_PENDING'